In [ ]:
import pandas as pd
movies = pd.read_csv("/content/tmdb_5000_movies.csv")
movies.shape

(4803, 20)

In [ ]:
movies.columns
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
#select required columns
movies = movies[['title','overview','genres']]
movies.isnull().sum()

title       0
overview    3
genres      0
dtype: int64

In [ ]:
movies['overview']=movies['overview'].fillna(' ')
movies.isnull().sum()

title       0
overview    0
genres      0
dtype: int64

In [ ]:
import ast

def extract_genres(genres):
  genre_list = []
  for genre in ast.literal_eval(genres):
    genre_list.append(genre['name'])
  return " ".join(genre_list)

# Apply function to genres column
movies['genres'] = movies['genres'].apply(extract_genres)

# Check result
movies.head()

,title,overview,genres
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction

In [ ]:
# Create tags feature by combining overview and genres
movies['tags'] = movies['overview'] + " " + movies['genres']
movies.head()

#keep only necessary cols
movies =  movies[['title','tags']]
movies.head()

,title,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca..."

In [ ]:
#Data preporcessing
#convert tags into lower case
movies['tags']= movies['tags'].apply(lambda x:x.lower())
movies.head()

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
#initialize vector
cv = CountVectorizer(max_features=5000 ,stop_words='english')
#convet tags to vectors
vectors = cv.fit_transform(movies['tags']).toarray()
vectors.shape
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
#calculate cosine similarity
similarity = cosine_similarity(vectors)
similarity.shape

(4803, 4803)

In [ ]:
#create function to recommend movies
def recommend(movie):
  #get index of the movie
  movie_index = movies[movies['title']==movie].index[0]

  #get similarity score
  distances = similarity[movie_index]

  #sort movies based on similarity scores
  movies_list = sorted(
      list(enumerate(distances)),
      reverse=True,
      key=lambda x:x[1]
  )
  #return top 5 similar movies (excluding itself)
  recommend_movies = []
  for i in movies_list[1:6]:
    recommend_movies.append(movies.iloc[i[0]].title)
  return recommend_movies

In [ ]:
recommend('Avatar')

['Beowulf',
 'The Helix... Loaded',
 'Small Soldiers',
 'Iron Man 3',
 'Journey 2: The Mysterious Island']

In [ ]:
import pickle

pickle.dump(movies, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [ ]:
from google.colab import files
files.download('movies.pkl')
files.download('similarity.pkl')